import { useState } from 'react';
import { Text,View,Pressable } from 'react-native';
import { router } from 'expo-router';
import { useData } from '../../src/store';
import { Page,Card,Button,styles,colors,when } from '../../src/ui';
const dayKey=(d:Date)=>`${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;
export default function MyCalendar(){
 const {plans}=useData();const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const [selected,setSelected]=useState<string|null>(null);
 const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();
 const visible=plans.filter(p=>{const date=new Date(p.start);return selected?dayKey(date)===selected:date.getMonth()===month.getMonth()&&date.getFullYear()===month.getFullYear()});
 function move(n:number){setMonth(new Date(month.getFullYear(),month.getMonth()+n,1));setSelected(null)}
 return <Page><Text style={styles.eyebrow}>MAKE ROOM FOR THE GOOD STUFF</Text><Text style={styles.title}>My calendar</Text><Button title="+ Create a plan" onPress={()=>router.push('/plan')}/><Card><View style={styles.row}><Button title="‹" onPress={()=>move(-1)}/><Text style={styles.heading}>{month.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</Text><Button title="›" onPress={()=>move(1)}/></View><View style={{flexDirection:'row',flexWrap:'wrap'}}>{['S','M','T','W','T','F','S'].map((d,i)=><Text key={i} style={{width:'14.28%',textAlign:'center',color:colors.muted,paddingVertical:10}}>{d}</Text>)}{Array.from({length:month.getDay()},(_,i)=><View key={'blank'+i} style={{width:'14.28%'}}/>)}{Array.from({length:days},(_,i)=>{const key=dayKey(new Date(month.getFullYear(),month.getMonth(),i+1));const has=plans.some(p=>dayKey(new Date(p.start))===key);return <Pressable key={key} accessibilityRole="button" accessibilityLabel={`${month.toLocaleDateString(undefined,{month:'long'})} ${i+1}${has?', has plans':''}`} onPress={()=>setSelected(selected===key?null:key)} style={{width:'14.28%',height:48,alignItems:'center',justifyContent:'center',backgroundColor:selected===key?colors.harbor:'transparent',borderRadius:12}}><Text style={{color:selected===key?'white':colors.ink}}>{i+1}</Text><Text style={{color:selected===key?'white':colors.harbor,fontSize:9}}>{has?'●':' '}</Text></Pressable>})}</View>{selected&&<Button title="Show whole month" onPress={()=>setSelected(null)}/>}</Card>{visible.length?visible.map(p=><Card key={p.id}><Text style={styles.eyebrow}>{when(p.start)}</Text><Text style={styles.heading}>{p.title}</Text><Text style={styles.body}>{p.location}</Text><Button title="View plan & calendar status" onPress={()=>router.push({pathname:'/plan',params:{id:p.id}})}/></Card>):<Text style={styles.body}>No plans {selected?'on this day':'this month'} yet.</Text>}</Page>
}
