import { ReactNode } from 'react';
import { ScrollView,Text,Pressable,View,StyleSheet,Linking,Alert,RefreshControl } from 'react-native';
export const colors={paper:'#f2f3f1',ink:'#1a2330',muted:'#5c6672',harbor:'#3a6361',fog:'#d5dad7',signal:'#c45c26',uvaBlue:'#232D4B',uvaOrange:'#F84C1E'};
export const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.paper},content:{padding:22,paddingBottom:48,gap:18},eyebrow:{fontSize:12,fontWeight:'700',letterSpacing:2,color:colors.harbor},title:{fontSize:36,fontWeight:'700',color:colors.ink},heading:{fontSize:23,fontWeight:'600',color:colors.ink},body:{fontSize:16,lineHeight:24,color:colors.muted},card:{backgroundColor:'white',borderRadius:20,padding:20,gap:12,borderWidth:1,borderColor:colors.fog},row:{flexDirection:'row',gap:10,flexWrap:'wrap',alignItems:'center'},button:{backgroundColor:colors.harbor,borderRadius:12,paddingHorizontal:18,paddingVertical:14,minHeight:48,alignItems:'center'},buttonText:{color:'white',fontSize:16,fontWeight:'600'},input:{backgroundColor:'white',borderWidth:1,borderColor:colors.fog,borderRadius:12,padding:14,fontSize:17,color:colors.ink,minHeight:50}});
export function Page({children,refreshing=false,onRefresh}:{children:ReactNode;refreshing?:boolean;onRefresh?:()=>void}){return <ScrollView style={styles.page} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={onRefresh?<RefreshControl refreshing={refreshing} onRefresh={onRefresh}/>:undefined}>{children}</ScrollView>}
export function Button({title,onPress,disabled=false}:{title:string;onPress:()=>void;disabled?:boolean}){return <Pressable accessibilityRole="button" accessibilityState={{disabled}} disabled={disabled} onPress={onPress} style={[styles.button,disabled&&{opacity:0.5}]}><Text style={styles.buttonText}>{title}</Text></Pressable>}
export function Card({children}:{children:ReactNode}){return <View style={styles.card}>{children}</View>}
export function problem(error:unknown){Alert.alert('My Vibe',error instanceof Error?error.message:'Something went wrong. Please try again.');}
export async function openLink(url:string){try{if(!/^https?:\/\//i.test(url)) throw new Error('This link is not supported.');await Linking.openURL(url);}catch(e){problem(e)}}
export const when=(iso:string)=>new Date(iso).toLocaleString(undefined,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
